// __tests__/utils/formatter.test.ts
// Auto-generated by Kiro
import { describe, it, expect } from 'vitest';
import { formatPrice, formatRelativeTime } from '../../src/utils/formatter';

describe('formatPrice', () => {
it('debe formatear correctamente un precio en MXN', () => {
const result = formatPrice(1500);
expect(result).toContain('1,500');
expect(result).toContain('MXN');
});

it('debe formatear correctamente decimales', () => {
const result = formatPrice(99.99);
expect(result).toContain('99.99');
});

it('debe formatear cero correctamente', () => {
const result = formatPrice(0);
expect(result).toBeDefined();
expect(typeof result).toBe('string');
});

it('debe rechazar montos negativos', () => {
expect(() => formatPrice(-100)).toThrow('Amount cannot be negative');
});

it('debe manejar números muy grandes', () => {
const result = formatPrice(1000000);
expect(result).toContain('1,000,000');
});
});

describe('formatRelativeTime', () => {
it('debe retornar "ahora mismo" para fechas muy recientes', () => {
const now = new Date();
const result = formatRelativeTime(now);
expect(result).toBe('ahora mismo');
});

it('debe formatear minutos correctamente', () => {
const fiveMinutesAgo = new Date(Date.now() - 5 * 60000);
const result = formatRelativeTime(fiveMinutesAgo);
expect(result).toBe('hace 5 minutos');
});

it('debe usar singular para un minuto', () => {
const oneMinuteAgo = new Date(Date.now() - 60000);
const result = formatRelativeTime(oneMinuteAgo);
expect(result).toBe('hace 1 minuto');
});

it('debe formatear horas correctamente', () => {
const twoHoursAgo = new Date(Date.now() - 2 * 60 * 60000);
const result = formatRelativeTime(twoHoursAgo);
expect(result).toBe('hace 2 horas');
});

it('debe formatear días correctamente', () => {
const threeDaysAgo = new Date(Date.now() - 3 * 24 * 60 * 60000);
const result = formatRelativeTime(threeDaysAgo);
expect(result).toBe('hace 3 días');
});

it('debe usar singular para un día', () => {
const oneDayAgo = new Date(Date.now() - 24 * 60 * 60000);
const result = formatRelativeTime(oneDayAgo);
expect(result).toBe('hace 1 día');
});
});
