// __tests__/auth/password-validator.test.ts
// Auto-generated by Kiro
import { describe, it, expect } from 'vitest';
import { PasswordValidator } from '../../src/auth/password-validator';

describe('PasswordValidator - Spec Compliance', () => {
let validator: PasswordValidator;

beforeEach(() => {
validator = new PasswordValidator();
});

describe('Requirement 2.1: Password Validation', () => {
// Validates: Requirement 2.1.1
it('debe rechazar password con menos de 8 caracteres con mensaje específico', () =>
